---
- name: Restart autofs
  ansible.builtin.service:
    name: autofs.service
    state: restarted

- name: Restart backup
  ansible.builtin.systemd:
    name: backup.timer
    state: restarted
    daemon_reload: true
